### PR TITLE
ENH: OpenSeadragon for map displays & new layout for search results

### PR DESCRIPTION
**Pull request by pastewka**
This is a draft MR for enabling map display through OpenSeadragon. Task breakdown:

- [x] Write DZI topography images to S3
- [x] Render using OpenSeadragon
- [x] Remove DZI from S3 when topography is removed
- [x] Write DZI images to S3 for analysis results that have maps (e.g. contact mechanics)
- [x] Render analysis results using OpenSeadragon
- [x] Remove DZI from S3 when analysis is removed

### CODE REVIEW

**Comment by pastewka** [comment]
The views of 2D maps now work as I renvisioned them. Note that the you need a development version of `SurfaceTopography` to run this.

I need a bit of help at this point @mcrot :
1) How do I add a JS library (OpenSeadragon) to the project properly? Is there a package manager that I need to use. I just dumped them in `static/js` for now.
2) Do I need to take care of deleting analysis results or is everything beneath `/media/analyses/XXX` simply removed if the analysis disappears.
3) I am generating a set of files (Deep Zoom Images) for each topography. They are currently dumped into `/media/topographies` (the derived `squeezed` files are also there). Is this the right place or should we have a `/media/derived` for dependent but derived data? How do I implementing deleting these files when the topgography disappears?

**Comment by pastewka** [comment]
Things left to do:
- [] Display of topographies with aspect ratio != 1

**Comment by pastewka** [comment]
I've created an issue for the aspect ratio #764

**Comment by pastewka** [comment]
Hi @mcrot - I think this is ready for your review

**Comment by pastewka** [comment]
Hi @mcrot - I'll be pushing a couple of updates to the tests

**Comment by pastewka** [comment]
This now tests creation and deletion of thumbnails and DZI files

**Comment by pastewka** [comment]
Hi @mcrot - I am reverting this to draft. Will address #769 and #479 here

**Comment by pastewka** [comment]
Hi @mcrot - in order to avoid loading the topography in the Django server, I had to remove the following check:

https://github.com/ContactEngineering/TopoBank/blob/63ab8506decbff914a6ee06efc464e20a8a1776b/topobank/manager/views.py#L439

This `renew_squeezed_datafile` is used to check whether the file is corrupted. However, I don't think we need this check, since the datafile is already opened here:

https://github.com/ContactEngineering/TopoBank/blob/63ab8506decbff914a6ee06efc464e20a8a1776b/topobank/manager/forms.py#L108

It is opened (i.e. metadata is read and parsed), but the data (i.e. height information) is not read. Do you know of a case where opening the file works but reading the data does not? The readers should make a guarantee that if the file can be opened, it will be possible to read data. (I can envision situations where the current readers do not guarantee this, but this would be weirdly malformed files.)

**Comment by pastewka** [comment]
Final todo is to store bandwidth in database.

**Comment by mcrot** [comment]
> It is opened (i.e. metadata is read and parsed), but the data (i.e. height information) is not read. Do you know of a case where opening the file works but reading the data does not? The readers should make a guarantee that if the file can be opened, it will be possible to read data. (I can envision situations where the current readers do not guarantee this, but this would be weirdly malformed files.)

This check was introduced here: #340 .
No, I don't know of such a case except the ones I've created artificially. I think I just wanted to make
sure that there is only valid data in the system.

So for me it's okay to remove to check. Maybe we should make sure that the size of measurements is limited,
so too large measurements will not fill up the memory of the analyses server again and again?! Also see #410.

**Comment by pastewka** [comment]
Okay, I will look at your checks. I think this needs to be handled on the `SurfaceTopography` side. If there is a data buffer, the readers should check whether the file is actually large enough to contain it. Many readers already do that implicitly, but not all.

**Comment by pastewka** [comment]
(Note that since it now runs in Celery, it won't produce an internal server error.)

**Comment by pastewka** [comment]
Hi @mcrot - this PR is ready for your review. It is also addressing the issue of avoiding to load the topography within the Django server. (It still does that for line scans, but that is okay.)

**Comment by mcrot** [comment]
Great, thanks! I'll have a look.

**Review by mcrot — APPROVED** [review]
Looks good. I've added the PNG download buttons for contact mechanics.
I've tried to show another indicator because sometimes it takes some more 
seconds on my laptop to show the map when the view has already loaded, but
I haven't found a suitable event in OpenSeaDragon - maybe later.

I'll try to fix the basket and menu position in another issue in order to have this PR finished.

**Comment by pastewka** [comment]
Closes #743

**Pull request merged**
