### PR TITLE
MAINT: Bumped SurfaceTopography version to 1.2.2

### PR DESCRIPTION
**Pull request by pastewka**
Updated SurfaceTopography version to 1.2.1, which introduces a Park Systems TIFF reader and crucial bug fixes for VK3 and X3P readers.

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @mcrot - can you have a look at this failure? It looks like it may have to do with the serializer issue that you recently dealt with.

**Comment by mcrot** [comment]
Yes, I'll have a look. I've stumbled across the same issue.

**Comment by pastewka** [comment]
I will also release 1.2.2 which has related bug fixes.

**Comment by pastewka** [comment]
Just bumped to 1.2.2

**Comment by mcrot** [comment]
I'll stick with 1.2.2 because with 1.2.3 I have installation problems.

**Review by mcrot — APPROVED** [review]

**Review by mcrot — APPROVED** [review]

**Pull request merged**
