### PR TITLE
ENH: Reliability analyis, scale-dependent roughness parameters, and refactored averaging/resampling of data points

### LINKED ISSUE #696: Deselection takes long in Power Spectrum plot for UNCD
The UNCD surface has more than 160 measurements.
When opening the Power Spectrum plot, the deselection and selection of all datasets in the plot
takes much time in the browser. 
Interestingly, another plot like Slope Distribution is quite fast in comparison. The Slope Distribution plot has
2 datasets per topography while the power spectrum plot has 3. Maybe there is some threshold about 350 datasets
after which it becomes slow for some reason?

### PR DESCRIPTION
**Pull request by pastewka**
This PR implements:
* Reliability analysis for scanning probe measurements (see arXiv:2106.16103)
* Scale-dependent roughness parameters (also arXiv:2106.16103)
* Resampling/averaging of data has been moved to `SurfaceTopography`

Closes #696, #687, #586, #83

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @mcrot - this draft PR shows you what I am presently working on.

See also https://github.com/ContactEngineering/SurfaceTopography/pull/138 for required changes on the `SurfaceTopography` end

**Comment by mcrot** [comment]
This looks ok overall, but I'm just trying to analyze the surface from #724 with this branch and a worker throws this message:
```python3
[2021-09-22 18:07:30,366: ERROR/ForkPoolWorker-7] Task topobank.taskapp.tasks.perform_analysis[dc485d57-eb86-4108-a6ef-01fc9d057fcf] raised unexpected: TypeError("power_spectrum_from_profile() got an unexpected keyword argument 'kwargs'")
Traceback (most recent call last):
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/taskapp/tasks.py", line 129, in perform_analysis
    result = analysis.function.eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 288, in eval
    return self.get_implementation(subject_type).eval(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/models.py", line 340, in eval
    return pyfunc(subject, **kwargs)
  File "/home/michael/work/imtek/topobank/topobank/analysis/functions.py", line 576, in power_spectrum_for_surface
    return analysis_function_for_surface(surface,
  File "/home/michael/work/imtek/topobank/topobank/analysis/functions.py", line 527, in analysis_function_for_surface
    r, A = log_average(topographies, funcname_profile, unit, progress_callback=progress_callback, **kwargs)
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/Container/Averaging.py", line 70, in log_average
    x, y = func(reliable=reliable, resampling_method=None, **kwargs)
  File "/home/michael/work/imtek/topobank/venv/lib/python3.8/site-packages/SurfaceTopography/HeightContainer.py", line 89, in func
    return self._functions[name](self, *args, **kwargs)
TypeError: power_spectrum_from_profile() got an unexpected keyword argument 'kwargs'
```
I'll have to continue tomorrow, but it seems there is still some problem. Maybe just adding `kwargs` fixes it..

**Comment by pastewka** [comment]
I can also check tomorrow. I've seen this today but rerunning the calculations actually worked.

**Comment by mcrot** [comment]
I'm having a look now.

**Comment by pastewka** [comment]
I was trying to simply pass on all keyword parameters to the analysis function: Django may be confused by this. If this does not work, reintroduce the `window` parameter for power spectrum analysis and all analysis methods should probably have an `nb_points_per_decade` parameter that is passed through to `SurfaceTopography`.

**Comment by mcrot** [comment]
I think the problem is, that you've added `**kwargs` arguments to the new functions. Through introspection they
are saved in the database as analysis arguments and passed as extra keyword argument to the analyses:
grafik
Do we need those? They cannot be set from outside I think, because when the analysis function is called by the worker, all arguments are taken from the pickled dict in the database.

**Comment by pastewka** [comment]
We don't need those. Let me fix this now.

**Comment by pastewka** [comment]
Hi @mcrot - the issue should be fixed. Can you double check?

**Comment by mcrot** [comment]
Thanks, yes I'm checking with the surface of #724, there's some problem on my side.

When that's okay, I will also merge the current develop here first before I merge it back to develop. I'll let you know.

**Comment by pastewka** [comment]
Sounds good!

**Review by mcrot — COMMENTED** [review]
Looks good!

**Pull request merged**
