### PR TITLE
BUG: Fixed datafile location during upload

### LINKED ISSUE #929: Wrong S3 storage location for raw data files
File should be stored under the `raw` prefix of the topograph, but are stored in the user directory.

#801 should have addressed this,.but apparently did not.

### PR DESCRIPTION
**Pull request by pastewka**
Closes #929

### CODE REVIEW

**Review by mcrot — APPROVED** [review]

**Review by mcrot — CHANGES_REQUESTED** [review]
Overall the code looks correct, but there is a problem in the tests: The "name" attribute is no longer filled correctly. Maybe we have to change the creation of test instances
to use the _upload_path_for_datafile function?! Not sure yet.

**Comment by mcrot** [comment]
Let me have a look at this when the "NaN" problem is solved.

**Comment by pastewka** [comment]
I'll look at the name issue, it would be good have the NaN issue resolved though.

**Comment by pastewka** [comment]
I think there was a missing `instance.save()`

**Comment by pastewka** [comment]
The problem is gone, only failure left is related to the NaN issue.

**Comment by mcrot** [comment]
Great, I'm looking at the NaN issue, I don't have a general solution yet. On Python level, on having `NaN` in JSON is simply ignored and the Parser simply interprets `NaN` (literal, not string) correctly. But when passing it to JS, we need `"NaN"`. I thought I have a solution already, but it only works for `NaN` in numpy arrays to far.

**Comment by mcrot** [comment]
We can delete this PR, correct?

**Comment by pastewka** [comment]
Yes

**Pull request closed without merging**
