### PR TITLE
22 unreliable bw 825 roettger

### PR DESCRIPTION
**Pull request by yaelgail**
Could you please look at these changes ? Does the unreliable bandwidth looks good when it's very little ?

### CODE REVIEW

**Comment by pastewka** [comment]
Code looks good, I have not run it yet will do so today or tomorrow.

**Review by pastewka — CHANGES_REQUESTED** [review]
1) If all bandwidth is reliable, there is still a little red box to the left. It may make sense to keep the cutoff as "None" to indicate that all data is realiable and not plot that box.

2) You need to recompute the short cutoff when the user changes the tip radius (or edits the instrument)

3) I would separate the creation of the squeezed data file from updating the bandwidth information. One reason is that now the computation of the reliability cutoff is probably the most time consuming part (and no longer the creation of the squeezed file). Also, you don't need to recreate the squeezed file when you edit the instrument.

Can you implement these 3 changes @yaelgail ?

**Comment by pastewka** [comment]
Here is a screenshot showing the red boxes for fully reliable measurements:

image

**Comment by pastewka** [comment]
I would also change the title here to "Measurement artifacts"

image

**Comment by pastewka** [comment]
PS: Can you also update the changelog?

**Review by mcrot — APPROVED** [review]

**Comment by mcrot** [comment]
> 1. If all bandwidth is reliable, there is still a little red box to the left. It may make sense to keep the cutoff as "None" to indicate that all data is realiable and not plot that box.
> 
>     2. You need to recompute the short cutoff when the user changes the tip radius (or edits the instrument)
> 
>     3. I would separate the creation of the squeezed data file from updating the bandwidth information. One reason is that now the computation of the reliability cutoff is probably the most time consuming part (and no longer the creation of the squeezed file). Also, you don't need to recreate the squeezed file when you edit the instrument.
> 
> 
> Can you implement these 3 changes @yaelgail ?

I've just implemented the third point.

**Review by mcrot — APPROVED** [review]

**Pull request merged**
