### PR TITLE
MAINT: Added django-watchman

### PR DESCRIPTION
**Pull request by pastewka**
django-watchman allows introspection of whether the endpoint is alive. This is useful to check the status of the app or to integrate it with a load balancer.

### CODE REVIEW

**Comment by pastewka** [comment]
@mcrot - do we need a test for this?

**Comment by mcrot** [comment]
I've added an additional check whether a celery worker is available.
For this check I've added test.

**Comment by mcrot** [comment]
For production I've added the need for being logged-in as staff member in order to request the watchman urls,
in order not to make it totally public. I've also added links to the user menu in the application that you can access
the watchman dashboard directly.

In future maybe we want a token authentication instead of the user authentication. It depends who or which process is looking for the status.

**Review by mcrot — APPROVED** [review]

**Comment by pastewka** [comment]
I have implemented a simple native health check

**Comment by mcrot** [comment]
Okay .. I think what is good about the celery worker check, is that we can identify connection losses to the workers.

**Comment by pastewka** [comment]
Agreed. Reopening this.

**Comment by pastewka** [comment]
Sorry for the mess, I didn't realize you had worked on this. Watchman is probably better in the long run as it offer more complete health information.

**Pull request merged**
